### ISSUE TITLE
doesn't work since node 6.4

### ISSUE THREAD

**Issue by florianleroux** [sidorares/node-i3#8]
example:
```js
var i3 = require('i3').createClient();

i3.tree((err,tree) => {
    console.log(tree);
});
```
stdout:
```
buffer.js:761
        return this.utf8Write(string, offset, length);
                    ^

RangeError: Offset is out of bounds
    at RangeError (native)
    at Buffer.write (buffer.js:761:21)
    at encodeCommand (/home/florian/node_modules/i3/lib/ipc.js:54:7)
    at I3IpcClient.message (/home/florian/node_modules/i3/lib/ipc.js:116:14)
    at I3IpcClient.tree (/home/florian/node_modules/i3/index.js:25:8)
    at Object.<anonymous> (/home/florian/test.js:3:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

```
node version 6.4.0
node-i3 version 0.2.0
i3 version 4.12
work perfecly with node 6.3.1

**Comment by sidorares** [comment]
Thanks!

I think node 6.4 is more strict about writing zero length string at the end of the buffer ( because length is there there would be no OOB write anyway but check errors earlier )

**Comment by sidorares** [comment]
This line https://github.com/sidorares/node-i3/blob/a62b5d76c262b99cfee6ff466a59d4e142919595/lib/ipc.js#L54

need to be wrapped in something like 

```js
if (payload.length > 0) {
  buf.write(payload, payloadOffset);
}
```

Also need to add changes similar to https://github.com/sidorares/node-mysql2/pull/381
 Instead `new Buffer(length)` use `Buffer.allocUnsafe(length)` + add `require('safe-buffer')` for older versions of node

Would you be able to try this yourself and make PR @florianleroux ?

**Comment by florianleroux** [comment]
The fix work
thanks
#9
